---
# This playbook setups BitNami Redmine servers.

- hosts: redmine-servers
  sudo: yes

  pre_tasks:
    - debug: var={{ item }}
      with_items:
        - bitnami_home

  roles:
    - common
    - expect
    - bitnami
    - redmine-settings
    - redmine-patches
    - redmine-plugins
    - redmine-themes
    - public
    - subversion
    - jdk
    - jenkins
