---
# debug.yml

- hosts: all

  tasks:
    - debug: var={{ item }}
      with_items:
        - inventory_hostname
        - ansible_ssh_user
        - bitnami_home
        - bitnami_path
        - redmine_home
        - svn_repos
        - git_repos
