---
# This playbook setups Subversion servers.

- hosts: subversion-servers
  sudo: yes

  pre_tasks:
    - debug: var={{ item }}
      with_items:
        - bitnami_home
        - svn_repos
        - git_repos

  roles:
    - common
    - expect
    - bitnami
    - redmine-settings
    - redmine-patches
    #- redmine-plugins
    - redmine-themes
    #- public
    - subversion
