---
# roles/redmine-patches/tasks/patch_locales.yml

- name: patch ja locale
  lineinfile: dest={{ redmine_home }}/config/locales/ja.yml
      regexp="{{ item.regexp }}" line="{{ item.line }}" backrefs=yes
  with_items:
    - regexp: '^( *label_age\:) +年齢$'
      line: '\1 経過期間'
  notify: restart bitnami-redmine
