---
# roles/bitnami/tasks/backup_mysql.yml

- name: backup mysql
  shell: >-
      mysqldump -ubitnami -p{{ bitnami_mysql_password }} bitnami_redmine
      > ~/tmp/bitnami_redmine{{ backup_suffix | default('') }}.sql
  environment:
    PATH: "{{ bitnami_path }}"
  changed_when: false
