---
# roles/redmine-settings/tasks/main.yml

- name: setup email settings
  replace:
    dest: "{{ redmine_home }}/config/configuration.yml"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - regexp: '^(  email_delivery\:)\n([^#]*\n)*'
      replace: '\1\n\n'
    - regexp: '^(  #  email_delivery\:)\n([^#]*\n)*'
      replace: '\1\n'
  notify: restart bitnami-redmine

- include: ../../bitnami/tasks/mysql_password.yml
- include: ../../bitnami/tasks/backup_mysql.yml
  vars:
    backup_suffix: -settings

- name: copy redmine_setup task
  copy:
    src: lib/tasks/redmine_setup.rake
    dest: "{{ redmine_home }}/lib/tasks/"

- name: setup redmine
  command: bundle exec rake redmine_setup RAILS_ENV=production
      chdir={{ redmine_home }}
  environment:
    PATH: "{{ bitnami_path }}"
    redmine_title: "{{ redmine_title | default('') }}"
    redmine_host: "{{ inventory_hostname }}"
    redmine_admin_fullname: "{{ bitnami_base_user_name | default('Admin Redmine') }}"
    redmine_admin_username: "{{ bitnami_base_user | default('admin') }}"
  register: result
  changed_when: "'updated' in result.stdout"
